name: 'Karate testing'
description: 'Run Karate tests'
author: 'Erik Bos'
inputs:
  vars:
    description: "One or more variables that become Karata script variables."
    required: false
  tests:
    description: 'Karata file or directory path with tests.'
    required: true
runs:
  using: docker
  image: Dockerfile