name: 'Karate testing'
description: 'Run Karate tests'
author: 'Erik Bos'
inputs:
  url:
    description: "URL to pass as url script variable."
    required: false
  tests:
    description: 'Karata file or directory path with tests.'
    required: true
runs:
  using: docker
  image: Dockerfile